version: '3'
services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8000:8000"

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server
    environment:
      - HOST=server
